M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date su  4. kesäkuuta 2023 18.11.03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-04T18:11:03+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X70.56Y-76.225
X70.56Y-80.225
T2
X118.45Y-100.575
X126.45Y-100.575
T0
M30
